name: 'Prepare CI'
description: 'Prepares feature flags'
inputs:
  extra-features:
    description: 'Extra feature flags to enable'
    required: false
    default: ''
  test-dependencies:
    description: 'Include test dependencies'
    required: false
    default: true
outputs:
  feature-flags:
    description: 'Feature flags'
    value: ${{ steps.prepare.outputs.flags }}
runs:
  using: 'composite'
  steps:
    - id: test
      shell: bash
      run: echo "feature=test-dependencies" >> $GITHUB_OUTPUT
      if: inputs.test-dependencies == 'true'

    # `steps.test.outputs.feature` cannot expand into attacker-controllable code
    # because the previous step only enables it to have one of two fixed values.
    - name: Prepare feature flags # zizmor: ignore[template-injection]
      id: prepare
      shell: bash
      run: >
        echo "flags=--features '
        bundled-prover
        download-params
        lightwalletd-tonic
        sync
        temporary-zcashd
        transparent-inputs
        unstable
        unstable-serialization
        unstable-spanning-tree
        ${EXTRA_FEATURES}
        ${{ steps.test.outputs.feature }}
        '" >> $GITHUB_OUTPUT
      env:
        EXTRA_FEATURES: ${{ inputs.extra-features }}
